#!/usr/bin/env bash

# debug
# set -x

if [[ "$1" == "ac" ]]
then # Arg copy
  CM=$0
  shift 1
  echo "$@" | $CM c
  exit $?
fi

autodetect_backend () {
  # Based on https://stackoverflow.com/a/8597411/539470
  if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    if [[ "$XDG_SESSION_TYPE" == "wayland" ]]; then
      echo wl-clipboard
    else # consider this as fallback for Linux
      echo xclip
    fi
  elif [[ "$OSTYPE" == "linux-android"* ]]; then
    echo termux-clipboard
  elif [[ "$OSTYPE" == "darwin"* ]]; then
    echo pbcopypaste
  elif [[ "$OSTYPE" == "cygwin" || "$OSTYPE" == "msys" || "$OSTYPE" == "win32" ]]; then
    echo powershell
  elif [[ "$OSTYPE" == "freebsd"* ]]; then
    echo xclip
  else                                         echo 
    >&2 echo "No idea on backend for OSTYPE '$OSTYPE'"
    echo
    exit -1
  fi
}

psh_clip_copy () {
  TMP_TXT=$(mktemp -p $TMP copy_XXXXXX.txt)
  cat >$TMP_TXT
  unix2dos -o -q $TMP_TXT
  powershell.exe -noprofile -command "[IO.File]::ReadAllText('$(cygpath -ma $TMP_TXT)', (New-Object System.Text.UTF8Encoding \$False)) | Set-Clipboard"
  rm $TMP_TXT
}

psh_clip_paste() {
  TMP_TXT=$(mktemp -p $TMP paste_XXXXXX.txt)
  powershell.exe -noprofile -command "Get-Clipboard | Set-Content -Encoding utf8 -Path '$(cygpath -ma $TMP_TXT)'" >/dev/null
  dos2unix -o -q $TMP_TXT
  head -c -1 $TMP_TXT # Skip trailing newline
  rm $TMP_TXT
}

if [ -z "$CCCP_BACKEND" ]
then # get if from config (preferred) of autodetect
  CH="${XDG_CONFIG_HOME:-$HOME/.config}"
  if [ -r "$CH/cccp.conf" ]
  then
    . $CH/cccp.conf
  else
    BACKEND=$(autodetect_backend)
  fi
else # or override
  BACKEND=$CCCP_BACKEND
fi

case $BACKEND in
  pbcopypaste)
    COPY='pbcopy'
    PASTE='pbpaste'
  ;;
  xclip)
    COPY='xclip -selection clipboard -in'
    PASTE='xclip -selection clipboard -out'
  ;;
  wl-clipboard)
    COPY='wl-copy'
    PASTE='wl-paste'
  ;;
  termux-clipboard)
    COPY='termux-clipboard-set'
    PASTE='termux-clipboard-get'
  ;;
  powershell)
    # Scripting for Windows is, as usual, a kind of feast.
    PASTE='psh_clip_paste'
    COPY='psh_clip_copy'
  ;;
  *)
    >&2 echo "Backend '$BACKEND' not supported"
    exit -1
  ;;
esac

case $1 in
  c)
    eval $COPY
    exit $?
  ;;
  p)
    eval $PASTE
    exit $?
  ;;
  '')
    echo '`cccp c` -- copy STDIN to clipboard'
    echo '`cccp p` -- paste clipboard to STDOUT'
    echo '`cccp ac whatever you want` -- copy `whatever you want` to clipboard'
  ;;
  *)
    >&2 echo "Command '$1' not supported"
    exit -1
  ;;
esac
