#!/usr/bin/env bash

# shellcheck disable=SC2016,SC2164,SC2174
# We know:
#   - SC2016 when to use single or double quotes,
#   - SC2174 what mode we do want,
#   - SC2164 where to pushd so it should not fail =)

# To debug, uncomment
# set -x

op=$1
shift 1

path2uri() {
  local abs_path
  abs_path=$(readlink -f "$1")
  echo "$abs_path" | python3 -c 'import pathlib; print(pathlib.Path(input()).as_uri())'
}

uri2path() {
  echo "$1" | python3 -c "import urllib.parse; print(urllib.parse.unquote(input().replace('file://', '')))"
}

ccfiles() {
  local op
  op=$1
  shift 1

#  {
#    for fn in $@; do
#      path2uri "$fn"
#    done
#  } | {
#    CCCP_MIME=text/uri-list cccp c
#  }

  {
    echo $op
    for fn in "$@"; do
      path2uri "$fn"
    done
  } | {
    CCCP_MIME=x-special/gnome-copied-files cccp c
  }

}

pfiles() {
  {
    CCCP_MIME='x-special/gnome-copied-files' cccp p
    echo # newline
  } | {
    local op
    local cmd
    read -r op
    [[ $op == 'cut' ]] && cmd='mv' || cmd='cp'

    while IFS= read -r l; do
      $cmd "$(uri2path "$l")" .
    done
  }

  CCCP_MIME='x-special/gnome-copied-files' cccp ac
}

case $op in
  copy)
    ccfiles copy "$@"
  ;;
  cut)
    ccfiles cut "$@"
  ;;
  paste)
    pfiles
  ;;
  *)
    >&2 echo "Command '$op' not supported"
    exit 1
  ;;
esac
