#!/usr/bin/env bash

# shellcheck disable=SC2016,SC2164,SC2174
# We know:
#   - SC2016 when to use single or double quotes,
#   - SC2174 what mode we do want,
#   - SC2164 where to pushd so it should not fail =)

# To debug, uncomment
# set -x

op=$1
shift 1

path2uri() {
  local abs_path
  abs_path=$(readlink -f "$1")
  echo "$abs_path" | python3 -c 'import pathlib; print(pathlib.Path(input()).as_uri())'
}

uri2path() {
  echo "$1" | python3 -c "import urllib.parse; print(urllib.parse.unquote(input().replace('file://', '')))"
}

ccfiles() {
  local op
  op=$1
  shift 1

  # sane cccp backends do not support multiple mimes in clipboard...
  # {
  #   for fn in $@; do
  #   path2uri "$fn"
  #   done
  # } | {
  #  CCCP_NO_NOHUP=true CCCP_MIME=text/uri-list cccp c
  # }

  {
    echo "$op"
    for fn in "$@"; do
      path2uri "$fn"
    done
  } | {
    CCCP_MIME=x-special/gnome-copied-files cccp c
  }

}

pfiles() {
  local op
  op=$1
  {
    CCCP_MIME='x-special/gnome-copied-files' cccp p
    echo # newline
  } | {
    if [[ $op == 'show' ]]; then
      cat
    else
      local fop
      local cmd
      read -r fop
      [[ $fop == 'cut' ]] && cmd='mv' || cmd='cp'

      while IFS= read -r l; do
        if [[ -n "$l" ]]; then
          $cmd "$(uri2path "$l")" .
        fi
      done

      CCCP_MIME='x-special/gnome-copied-files' cccp ac
    fi
  }
}

case $op in
  copy|c)
    ccfiles copy "$@"
  ;;
  cut|x)
    ccfiles cut "$@"
  ;;
  paste|v|p)
    pfiles paste
  ;;
  show|s)
    pfiles show
  ;;
  *)
    >&2 echo "Command '$op' not supported"
    exit 1
  ;;
esac
